# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_topic_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
