# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='board',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='starter',
        ),
        migrations.AddField(
            model_name='topic',
            name='direction',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='staff',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='teachers',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Lab',
        ),
    ]
