# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-10 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0007_auto_20190606_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='delegation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Topic'),
        ),
        migrations.AddField(
            model_name='delegation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='staffs',
            field=models.ManyToManyField(related_name='joins', through='boards.Delegation', to=settings.AUTH_USER_MODEL),
        ),
    ]
