# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-11 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20190611_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_staffs', to='boards.Topic'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='del_joins', to=settings.AUTH_USER_MODEL),
        ),
    ]
