# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-06-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20190611_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='percent',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='state',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
