# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190520_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='project',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
