# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-20 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20190520_0851'),
        ('accounts', '0005_auto_20190520_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favered', to='boards.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faverer', to='accounts.User')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
